### PR TITLE
fix(deploy): update for game version 3.210.2

### PR DESCRIPTION
**Pull request by AnthonyFuller**
As title

### CODE REVIEW

**Comment by ILoveMyKittyCats** [comment]
Its not updating for me

**Comment by AnthonyFuller** [comment]
The update was just released.

**Comment by AndrewDaPro6969** [comment]
it wont let me update

**Comment by JojjeE** [comment]
So do it manually. https://github.com/atampy25/simple-mod-framework/releases/latest/download/Release.zip

**Comment by AndrewDaPro6969** [comment]
so what do i do with the new zip?

**Comment by AndrewDaPro6969** [comment]
should i unisntall the original giles?

**Comment by JojjeE** [comment]
Replace all files but config.json oughta do it

**Comment by AndrewDaPro6969** [comment]
i can reinstall the mods if i feel like it

**Comment by AndrewDaPro6969** [comment]
also, how to exit the github page on the original loader

**Comment by AndrewDaPro6969** [comment]
I thought you meant to removce them first. it is now broken

**Comment by AnthonyFuller** [comment]
Delete the Simple Mod Framework folder and re-install it using the installer found [on Nexus](https://www.nexusmods.com/hitman3/mods/200). Your install is a lost cause. If you still have mods in your mods folder, copy the `Mods` folder and `config.json` outside of the folder before deleting it and copy them into the newly installed instance of SMF.

**Pull request merged**
